### PR TITLE
upgrade(Ionic): Updated to Ionic 3.2.1

### LINKED ISSUE #27: Ionic 3 support
I had an existing Ionic 2.4.8, and followed the tutorial by @roblouie to add unit tests.
Which worked great.

I'm in the process of upgrading to Ionic 3, using the [ChangeLog Steps](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#steps-to-upgrade).

I've followed it, step by step but unit tests are now broken.

I see you have a [pull request](https://github.com/driftyco/ionic-unit-testing-example/pull/26) by @MTechDE. 

Is this master branch going to work with ionic 3.x? I can't find the branch for ionic 3 package.json version and file changes.

### PR DESCRIPTION
**Pull request by danielsogl**
- Updated the dependencies for Ionic 3.1.1
- typo

fix #27

### CODE REVIEW

**Comment by leifwells** [comment]
I am considering merging this PR into a v3 branch and keeping the master for v2 for the time being. Or vise versa. 

The main point is that I'd like to continue to support v2 for a bit longer.

Thoughts?

**Comment by MTechDE** [comment]
Sure, why not 👍 In my opinion the master branch should be the updated one.

**Comment by mlynch** [comment]
@MTechDE @leifwells agreed, v3 should be master and it'd make more sense to move v2 to a separate branch

**Comment by leifwells** [comment]
OK, I'll get that done ASAP.

**Comment by MTechDE** [comment]
I updated my PR to Ionic 3.1.1

**Comment by tobika** [comment]
@danielsogl just tried your PR except a little error in the package.json it works fine :)
`    "@ionic/cli-build-ionic-angular": "0.0.3",
    "@ionic/cli-plugin-cordova": "0.0.9",`
I used the original values of this packages because the ones in your package.json doesn't seem to exist when doing npm install. Or it was a problem with my system?

**Comment by danielsogl** [comment]
I should remove the CLI packages.

**Comment by danielsogl** [comment]
@leifwells I updated the PR and included your fix `IonicModule.forRoot(MyApp, {}, { links: [] })`

**Comment by Lightheaded** [comment]
Would really like to see this merged now that it works nicely. Also keeping it up to date would be really helpful. Having an easily testable framework is the dream, isn't it :)

**Comment by leifwells** [comment]
I will be merging this in as once I can test it. Thanks everyone for your hard work.

**Comment by danielsogl** [comment]
@leifwells I update to Ionic 3.2

**Comment by neilbo** [comment]
Just wanted to say thanks to @danielsogl and co for fixing this. Love OSS.

**Pull request merged**
